name: Test IDs Regression Tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        ruby-version: [2.5, 2.6]
    
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Update Env
      run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
    - name: Install Bundler
      run: gem install bundler:1.16.1
    - name: Bundler Update
      run: bundle update
    - name: Install dependencies
      run: bundle install  
    - name: Gem Install Origen 
      run: gem install origen 
    - name: Setup Dependencies
      run: origen -v
    - name: Run tests
      run: origen specs
